name: roasterscoffee
favicon: null
layout_spectrum: 0.49445
typography_spectrum: 0.60929
title: Roasters Coffee
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#010101'
    - '#b49d8b'
    - '#fff9ff'
    - '#946a3a'
    - '#644624'
  brandStrength: 0.8125
  lightness: 0.5625
  saturation: 0.5
  rhythmicContrast: 0.8549014599993825
purpose: []
