name: roasterscoffee
favicon: null
layout_spectrum: 0.97193
typography_spectrum: 0.60929
title: Roasters Coffee
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fcf8ed'
    - '#000000'
    - '#3d342f'
    - '#9b1629'
    - '#7f7a80'
  brandStrength: 0.8125
  lightness: 0.5625
  saturation: 0.5
  rhythmicContrast: 0.8549014599993825
purpose: []
